version: '3'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb02
    ports:
      - 3316:3306
    environment:
      - MARIADB_ROOT_PASSWORD=12345678
      - TZ='Asia/Taipei'
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    stdin_open: true
    tty: true
